### ISSUE TITLE
在文档里介绍一下原理

### ISSUE THREAD

**Issue by linonetwo** [oflg/fishing#1]
我比较想知道这几点：

1. 选了困难良好简单之后这个数据是保存到哪里，好像也没有保存到一个条目上的字段里
2. 这个复习记录只和标题有关吗？如果标题发生了改动之后该咋办？relink能处理吗？

**Comment by oflg** [comment]
数据保存在了当前复习条目的字段里（只不过被隐藏了），所以和标题无关
![image](https://user-images.githubusercontent.com/42492105/136771756-2c6c4693-4cf1-414c-ad0a-915e160464cb.png)

后续会把相关原理会更新在文档中

**Comment by linonetwo** [comment]
oh，我就奇怪为啥在字段那边还看不到呢

**Comment by oflg** [comment]
已经更新到文档中 https://oflg.github.io/fishing/#%E5%8F%8D%E9%A6%88
