### ISSUE TITLE
Internal JavaScript Error

### ISSUE THREAD

**Issue by wahidmounir** [oflg/fishing#17]
My tiddlywiki generate errors when tagging tiddlers with ? can I change this tag with another tag so it doesn't generate errors

The 1st Error:

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught TypeError: Cannot read properties of null (reading 'removeChild')

The 2nd Error

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
Uncaught SyntaxError: Invalid regular expression: /?|CodeMirror/: Nothing to repeat

**Comment by oflg** [comment]
Unfortunately it cannot be changed to other tags.

Based on the description so far, I can only tell that it's a CodeMirror issue.

You can try temporarily disabling CodeMirror and see if the same problem occurs.

You can also describe in detail the context in which the issue occurs and send a screenshot of the console log to see the exact problem.

**Comment by linonetwo** [comment]
Use developer tool to see acturial error location.
