### ISSUE TITLE
拆分出 npm 包

### ISSUE THREAD

**Issue by linonetwo** [oflg/fishing#18]
然后可以放到那个 opensrs 项目里。

还能改成用 ts 写算法。脚手架很简单，可以抄抄 https://github.com/tiddly-gittly/md-to-tid 的（这也是一个拆分出 npm 包，然后在插件里重新引用的情况）

**Comment by oflg** [comment]
就学着写（已新建文件夹👌

**Comment by oflg** [comment]
已写好，但还没发布 npm 包 https://github.com/open-spaced-repetition/free-spaced-repetition-scheduler/tree/main/fsrs.js

**Comment by linonetwo** [comment]
哈哈直接用 JS 写倒是省事了，不用编译了

**Comment by oflg** [comment]
刚好钓鱼里有 js，并且我也没学 ts。

已发布 npm 包：https://www.npmjs.com/package/fsrs.js
