### ISSUE TITLE
[BUG] Using the plugin on NodeJS server doesn't show icons down right on each tiddler

### ISSUE THREAD

**Issue by labibllaca** [oflg/fishing#23]
Hi, 
on the footer of each Tiddler three times comes this message:
`Undefined widget 'let'`
Also when I click the fish hook the same message appears three time and under that a inut with `[tag[?]]`.

Best regards

**Comment by oflg** [comment]
<$let> is a new widget for TW version 5.2.1. Please update TW to the latest version.

**Comment by labibllaca** [comment]
Thank you for being so helpful.  I've updated it through `sudo npm update -g tiddlywik`. Unfortunately on the 5.2.1 somehow doesn't show the dragged plugin on the page like before. But this is another matter I guess.

**Comment by oflg** [comment]
> Unfortunately on the 5.2.1 somehow doesn't show the dragged plugin on the page like before.

You can test it on an empty TW to find out the cause.

**Comment by labibllaca** [comment]
Thank you again. I close this now.
