### ISSUE TITLE
[IDEA] Using google translate for every language

### ISSUE THREAD

**Issue by labibllaca** [oflg/fishing#24]
Hi, 
as I keep using this peace of gold software, this needed feature may be easy to implement and helpful. So in the Fishing setting  in the ControllPanel there is under the features of Cachfish this parameter that can be changed for translating stuff in Chinese : URL of Word template with this parameter: `[{!!word}encodeuricomponent[]addprefix[https://dict.youdao.com/recite/words/#!/dict/engchn?le=eng&q=]]`

I though, how hard can it be to change the youdao dict and use there google or also other translation websites that are good at ?
- I\ve tried this link `https://translate.google.com/?sl=en&tl=es&text=#!&op=translate`  like this `[{!!word}encodeuricomponent[]addprefix[https://translate.google.com/?sl=en&tl=es&text=#!&op=translate]]` but without any result.

Any ideas how to make it work ?

Best regards.

**Comment by oflg** [comment]
The filter should be `[{!!word}encodeuricomponent[]addprefix[https://translate.google.com/?sl=en&tl=es&op=translate&text=]]`. But it still doesn't work, because Google Translate has a limitation that other sites can't embed its pages. You can follow this format and try other websites.

**Comment by labibllaca** [comment]
Thanks, @oflg. I've found until now just one website that let be embedded in a tiddle. Eventhough it loads the whole site in a tiddle, it works.
Here is the configuration for it:

`[{!!word}encodeuricomponent[]addprefix[https://www.reverso.net/text-translation#sl=eng&tl=ger&text=]] `

Greetings

**Comment by oflg** [comment]
The following website may also be ok.
```
dictionary.reference.com
ldoceonline.com
oxfordlearnersdictionaries.com
thefreedictionary.com
wiktionary.org
wordreference.com
```

**Comment by labibllaca** [comment]
That's great. See you in the next one :D @oflg .

**Comment by oflg** [comment]
![-7189f24eb5668fe4](https://user-images.githubusercontent.com/42492105/160242406-cccd6ed2-4b03-4598-94f4-da8472ee463d.jpg)
