### ISSUE TITLE
[BUG?] Links in tiddle not clickable after annotation

### ISSUE THREAD

**Issue by labibllaca** [oflg/fishing#25]
When I link another tiddle in the current I'm writing and save it I can hop to that tiddle by clicking it. But when I add this tiddle an `?`-tag and annotate some words or sentences, the words are covered blue, indicating I can learn them, but also make this tiddle only an 'flashcard'-like readable information. 
Is it possible to put the annotation color in the background so links on a tiddle can be clickable? I'd like to browse from tiddle to tiddle without typing it in a searchbar.

Greetings.

**Comment by labibllaca** [comment]
I get it that it's necessary to know which anottation is made, after a word or sentence is chosen. But the ability to click the link inside a tiddle is also important.
How about a switch button on each tiddle that has an annotation, that can activate and make appear the annotated word/sentence and vice versa when it's off ?

**Comment by oflg** [comment]
This blue highlighting feature relies on the Dynannotate plugin. 

Unfortunately, it does not have the ability to be clickable in the background. (You can't use both, you have to choose one or the other)

We can probably go to the TW repository and mention its issue or PR.

**Comment by oflg** [comment]
> How about a switch button on each tiddle that has an annotation, that can activate and make appear the annotated word/sentence and vice versa when it's off ?

I would consider making a switch setting.

**Comment by labibllaca** [comment]
What I've tied is: I click on a selected sentence, a mini tiddle opens, then I click on the edit button of this tiddle and format the tiddle by myself like adding origin links again by hand. Then the links work when this tiddle comes into popup after clicking on a notated text.
It's a workaround I can live with.

**Comment by oflg** [comment]
> It's a workaround I can live with.

Has it been solved?

I don't understand the problem very well (English is my second language).

Is there a relevant screenshot to be recorded to point out the problem?

**Comment by labibllaca** [comment]
我所做的是：我点击一个选定的句子，一个迷你的tiddle打开，然后我点击这个tiddle的编辑按钮，自己格式化这个tiddle，就像重新手工添加原点链接。然后，当我点击一个记号性的文本后，这个谜语进入弹出窗口时，这些链接就能发挥作用。
这是一个我可以接受的变通办法。

是的，问题已经解决了。谢谢你。
