### ISSUE TITLE
fishing插件显示异常 无法使用

### ISSUE THREAD

**Issue by jianfeixu95** [oflg/fishing#29]
fishing插件显示异常，麻烦帮忙看一下！谢谢！

TiddlyWiki version | 5.2.1

![fishing 插件显示异常1](https://user-images.githubusercontent.com/19361547/166470891-11121395-7151-4546-9437-bf6a6c254c41.jpg)
![fishing 插件新建tiddler时显示异常](https://user-images.githubusercontent.com/19361547/166470902-df135058-a153-4dce-9be3-468156fab838.jpg)

**Comment by oflg** [comment]
需要更新 tw 到最新版 v5.2.2

**Comment by neilxu95** [comment]
🙏感谢呀！

**Comment by jianfeixu95** [comment]
> 需要更新 tw 到最新版 v5.2.2

感谢呀！！谢谢
