### ISSUE TITLE
`[[When` insted of the normal tiddler to learn

### ISSUE THREAD

**Issue by labibllaca** [oflg/fishing#32]
Hi,
I somehow must have somthing in one of my tiddlies becouse from one moment to another as I was going though the learning process, by goint to the fish icon, click it then due/undue and then by clicking  Forget or Remember or Grasp or Discard.
But then when I clicked one of the four options, only ` [[When` comes in the title of the tiddle and nothing in the tiddle body. When I click to Forgot or Remeber ... this tiddle closes and another opens with the same title and empty body.
Is there any log-file I can give you without revealing all my tiddles ?

Cheers,
Labi

**Comment by oflg** [comment]
Is there a tiddler in the queue with special characters in the title, e.g. `[{|`. 

Special characters are not supported.

**Comment by labibllaca** [comment]
I had only ( and , in the title. But I also had stupid long titles. After I shortened all of them it works again.

**Comment by labibllaca** [comment]
Thanks for the quick response and help.
