### ISSUE TITLE
直接在页面展示按钮，只为间隔复习笔记使用，不影响独立卡片

### ISSUE THREAD

**Issue by dongrentianyu** [oflg/fishing#38]
比如展示两个按钮，是学习为摘录条目还是问题条目。一般就是学习为摘录条目了。如果里面有可以制成独立卡片的，可以由用户决定是用页面上的选中来生成新的卡片条目，还是剪切原条目内容来生成。

然后下面也可以展示一排按钮。这样每次遇到的时候就能自动复习一下了，特别是对摘录条目而言。

当然这个可以搞成全局设置。用户来决定要不要这样做。

**Comment by dongrentianyu** [comment]
因为我一直在想，钓鱼插件和supermemo对比究竟少了什么？

因为supermemo是直接把按钮放在下面的，而钓鱼插件还需要主动去点按钮然后控制复习。这个我觉得可能就会让人忘了使用钓鱼插件了。像我现在就除了独立的卡片外，很少去复习写的笔记内容。如果只复习做好的卡片，那就和anki差不多了。

还是能够间隔笔记复习内容。这样就好很多。

**Comment by dongrentianyu** [comment]
我试着自己能不能搞出来。如果能搞出来就提交pr，如果搞不出来，就只有等你来实现了。

**Comment by dongrentianyu** [comment]
不过这边是怎么构建测试页面的呢？我看`pnpm i`和`npm i`都行不通。

**Comment by dongrentianyu** [comment]
原来是在另一仓库里下载安装，现在已经搞好了基本环境了，我看自己能不能搞一下。

**Comment by dongrentianyu** [comment]
![image](https://github.com/oflg/fishing/assets/109711900/9cc65344-8049-4097-8cc1-efddadb36445)

但好像我修改的内容还是要这边提交了，那边才可能显示出来。而且这边只要是新建条目都会保存下来。但里面又没有文档内容。

现在不知道怎么办。

**Comment by dongrentianyu** [comment]
```
<$list
    filter="[<targetTiddler>!is[blank]] ~[list[$:/temp/fishing]first[]!is[blank]has[grade]]"
>
```

不过我看前面有用list来控制是否展示按钮。也就是实现了可以在通过桌面点击复习后才显示按钮。

**Comment by dongrentianyu** [comment]
我本来想模仿一下按钮自己本地搞一个，但好像行不能的样子。按钮是怎么操作变化那么多字段内容的。

![image](https://github.com/oflg/fishing/assets/109711900/919c9be3-5715-4838-b963-02d971a7c984)


例如我只是点了掌握，就有很多字段发生变化了。好像是通过`grade`字段，搭配js内容来变化的。我再试试能不能本地搞一下。

**Comment by dongrentianyu** [comment]
```
<$button>
<$action-sendmessage $message="tm-add-tag" $param="?" />
<$action-learn $grade="-1" />
learn
</$button>

<$button>	
<$fieldmangler>
<$action-sendmessage
$message="tm-add-tag"
 $param="?"
/>
</$fieldmangler>
<$action-learn
$grade="2"
/>
grasp
</$button>

<$button
class="forget tc-tiddlylink"
>	
<$action-learn
$grade="0"
 />
forget
</$button>
```

通过上面的代码基本上实现我想要的效果了。

**Comment by oflg** [comment]
> 不过这边是怎么构建测试页面的呢？我看`pnpm i`和`npm i`都行不通。

在 TiddlyMemo 项目下进行测试，详细方法见https://github.com/oflg/TiddlyMemo/blob/master/README-zh-Hans.md#%EF%B8%8F%E5%BC%80%E5%8F%91

**Comment by dongrentianyu** [comment]
这个没搞成功。思路和流程还有问题。先关闭了。
